spring.application.name=demoSnackbar
#database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/snackbar
spring.datasource.username=root
spring.datasource.password=test1234
#actuator
management.endpoints.web.exposure.include=health
#documentation
springdoc.api-docs.path=/api-docs